from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(352, 229)
        self.layoutWidget = QtWidgets.QWidget(Calculator)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 60, 352, 166))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.clear = QtWidgets.QPushButton(self.layoutWidget)
        self.clear.setCheckable(False)
        self.clear.setAutoRepeat(False)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 0, 0, 1, 1)
        self.plus_minus = QtWidgets.QPushButton(self.layoutWidget)
        self.plus_minus.setCheckable(False)
        self.plus_minus.setAutoRepeat(False)
        self.plus_minus.setObjectName("plus_minus")
        self.gridLayout.addWidget(self.plus_minus, 0, 1, 1, 1)
        self.percentage = QtWidgets.QPushButton(self.layoutWidget)
        self.percentage.setCheckable(False)
        self.percentage.setAutoRepeat(False)
        self.percentage.setObjectName("percentage")
        self.gridLayout.addWidget(self.percentage, 0, 2, 1, 1)
        self.divide = QtWidgets.QPushButton(self.layoutWidget)
        self.divide.setCheckable(False)
        self.divide.setAutoRepeat(False)
        self.divide.setObjectName("divide")
        self.gridLayout.addWidget(self.divide, 0, 3, 1, 1)
        self.seven = QtWidgets.QPushButton(self.layoutWidget)
        self.seven.setCheckable(False)
        self.seven.setAutoRepeat(False)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 1, 0, 1, 1)
        self.eight = QtWidgets.QPushButton(self.layoutWidget)
        self.eight.setCheckable(False)
        self.eight.setAutoRepeat(False)
        self.eight.setObjectName("eight")
        self.gridLayout.addWidget(self.eight, 1, 1, 1, 1)
        self.nine = QtWidgets.QPushButton(self.layoutWidget)
        self.nine.setCheckable(False)
        self.nine.setAutoRepeat(False)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 1, 2, 1, 1)
        self.multiply = QtWidgets.QPushButton(self.layoutWidget)
        self.multiply.setCheckable(False)
        self.multiply.setAutoRepeat(False)
        self.multiply.setObjectName("multiply")
        self.gridLayout.addWidget(self.multiply, 1, 3, 1, 1)
        self.four = QtWidgets.QPushButton(self.layoutWidget)
        self.four.setCheckable(False)
        self.four.setAutoRepeat(False)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 2, 0, 1, 1)
        self.five = QtWidgets.QPushButton(self.layoutWidget)
        self.five.setCheckable(False)
        self.five.setAutoRepeat(False)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 2, 1, 1, 1)
        self.six = QtWidgets.QPushButton(self.layoutWidget)
        self.six.setCheckable(False)
        self.six.setAutoRepeat(False)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 2, 2, 1, 1)
        self.minus = QtWidgets.QPushButton(self.layoutWidget)
        self.minus.setCheckable(False)
        self.minus.setAutoRepeat(False)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 2, 3, 1, 1)
        self.two = QtWidgets.QPushButton(self.layoutWidget)
        self.two.setCheckable(False)
        self.two.setAutoRepeat(False)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 3, 1, 1, 1)
        self.three = QtWidgets.QPushButton(self.layoutWidget)
        self.three.setCheckable(False)
        self.three.setAutoRepeat(False)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 3, 2, 1, 1)
        self.plus = QtWidgets.QPushButton(self.layoutWidget)
        self.plus.setCheckable(False)
        self.plus.setAutoRepeat(False)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 3, 3, 1, 1)
        self.zero = QtWidgets.QPushButton(self.layoutWidget)
        self.zero.setCheckable(False)
        self.zero.setAutoRepeat(False)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 4, 0, 1, 2)
        self.period = QtWidgets.QPushButton(self.layoutWidget)
        self.period.setCheckable(False)
        self.period.setAutoRepeat(False)
        self.period.setObjectName("period")
        self.gridLayout.addWidget(self.period, 4, 2, 1, 1)
        self.equals = QtWidgets.QPushButton(self.layoutWidget)
        self.equals.setCheckable(False)
        self.equals.setAutoRepeat(False)
        self.equals.setObjectName("equals")
        self.gridLayout.addWidget(self.equals, 4, 3, 1, 1)
        self.one = QtWidgets.QPushButton(self.layoutWidget)
        self.one.setCheckable(False)
        self.one.setAutoRepeat(False)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 3, 0, 1, 1)
        self.screen = QtWidgets.QLabel(Calculator)
        self.screen.setGeometry(QtCore.QRect(10, 10, 331, 41))
        self.screen.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.screen.setAutoFillBackground(False)
        self.screen.setText("")
        self.screen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.screen.setObjectName("screen")

        self.retranslateUi(Calculator)
        self.one.clicked.connect(self.screen.update)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Dialog"))
        self.clear.setText(_translate("Calculator", "AC"))
        self.plus_minus.setText(_translate("Calculator", "+/-"))
        self.percentage.setText(_translate("Calculator", "%"))
        self.divide.setText(_translate("Calculator", "/"))
        self.seven.setText(_translate("Calculator", "7"))
        self.eight.setText(_translate("Calculator", "8"))
        self.nine.setText(_translate("Calculator", "9"))
        self.multiply.setText(_translate("Calculator", "x"))
        self.four.setText(_translate("Calculator", "4"))
        self.five.setText(_translate("Calculator", "5"))
        self.six.setText(_translate("Calculator", "6"))
        self.minus.setText(_translate("Calculator", "-"))
        self.two.setText(_translate("Calculator", "2"))
        self.three.setText(_translate("Calculator", "3"))
        self.plus.setText(_translate("Calculator", "+"))
        self.zero.setText(_translate("Calculator", "0"))
        self.period.setText(_translate("Calculator", "."))
        self.equals.setText(_translate("Calculator", "="))
        self.one.setText(_translate("Calculator", "1"))
